<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Account\Account;
use App\Models\Account\AccountGroup;
use App\Models\Account\Cash;
use App\Models\Account\AccountHead;

class AccountSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Account::insert([
            [
                "id" => 1,
                "name" => strtoupper("Assets"),
                "code" => "01",
                "parent_id" => 0,
                "company_id" => 1,
                "added_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 2,
                "name" => strtoupper("Liabilities"),
                "code" => "02",
                "parent_id" => 0,
                "company_id" => 1,
                "added_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 3,
                "name" => strtoupper("Equity"),
                "code" => "03",
                "parent_id" => 0,
                "company_id" => 1,
                "added_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 4,
                "name" => strtoupper("Revenue"),
                "code" => "04",
                "parent_id" => 0,
                "company_id" => 1,
                "added_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 5,
                "name" => strtoupper("Expenses"),
                "code" => "05",
                "parent_id" => 0,
                "company_id" => 1,
                "added_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 6,
                "name" => strtoupper("Current Assets"),
                "code" => "01",
                "parent_id" => 1,
                "company_id" => 1,
                "added_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 7,
                "name" => strtoupper("Non Current Assets"),
                "code" => "02",
                "parent_id" => 1,
                "company_id" => 1,
                "added_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 8,
                "name" => strtoupper("Current Liabilities"),
                "code" => "01",
                "parent_id" => 2,
                "company_id" => 1,
                "added_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 9,
                "name" => strtoupper("Long term Liabilities"),
                "code" => "02",
                "parent_id" => 2,
                "company_id" => 1,
                "added_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 10,
                "name" => strtoupper("Shared Equity"),
                "code" => "01",
                "parent_id" => 3,
                "company_id" => 1,
                "added_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 11,
                "name" => strtoupper("Retained Earning"),
                "code" => "02",
                "parent_id" => 3,
                "company_id" => 1,
                "added_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 12,
                "name" => strtoupper("Other Income"),
                "code" => "01",
                "parent_id" => 4,
                "company_id" => 1,
                "added_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 13,
                "name" => strtoupper("SERVICE REVENUE, SALES"),
                "code" => "02",
                "parent_id" => 4,
                "company_id" => 1,
                "added_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 14,
                "name" => strtoupper("Cost of Good Sold"),
                "code" => "01",
                "parent_id" => 5,
                "company_id" => 1,
                "added_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 15,
                "name" => strtoupper("Operating Expenses"),
                "code" => "02",
                "parent_id" => 5,
                "company_id" => 1,
                "added_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
            ]
        ]);
        
        AccountGroup::insert([
            [
                "id" => 1,
                "name" => strtoupper("ACCRUED LIABILITIES"),
                "code" => "01",
                "account_id" => 8,
                "parent_id" => 0,
                "company_id" => 1,
                "added_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 2,
                "name" => strtoupper("SALARIES AND WAGES PAYABLE"),
                "code" => "001",
                "account_id" => 8,
                "parent_id" => 1,
                "company_id" => 1,
                "added_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 3,
                "name" => strtoupper("SALARIES, WAGES AND BENEFITS"),
                "code" => "01",
                "account_id" => 15,
                "parent_id" => 0,
                "company_id" => 1,
                "added_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 4,
                "name" => strtoupper("SALARIES EXPENSE"),
                "code" => "001",
                "account_id" => 15,
                "parent_id" => 3,
                "company_id" => 1,
                "added_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 5,
                "name" => strtoupper("ADVANCES, DEPOSITS, LOANS & PREPAYMENTS"),
                "code" => "01",
                "account_id" => 6,
                "parent_id" => 0,
                "company_id" => 1,
                "added_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 6,
                "name" => strtoupper("DEDUCTION OF EMPLOYEE AGT EXPENSES"),
                "code" => "001",
                "account_id" => 12,
                "parent_id" => 35,
                "company_id" => 1,
                "added_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 7,
                "name" => strtoupper("ADVANCE TO EMPLOYEE AGT SALARY"),
                "code" => "001",
                "account_id" => 6,
                "parent_id" => 5,
                "company_id" => 1,
                "added_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 8,
                "name" => strtoupper("LOAN TO EMPLOYEES"),
                "code" => "002",
                "account_id" => 6,
                "parent_id" => 5,
                "company_id" => 1,
                "added_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 9,
                "name" => strtoupper("Repair and Maintenance"),
                "code" => "02",
                "account_id" => 15,
                "parent_id" => 0,
                "company_id" => 1,
                "added_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 10,
                "name" => strtoupper("Repair and Maintenance - Vehicle"),
                "code" => "001",
                "account_id" => 15,
                "parent_id" => 9,
                "company_id" => 1,
                "added_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 11,
                "name" => strtoupper("VEHICLE SERVICE EXPENSE"),
                "code" => "03",
                "account_id" => 15,
                "parent_id" => 0,
                "company_id" => 1,
                "added_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 12,
                "name" => strtoupper("Vehicle Fuel"),
                "code" => "001",
                "account_id" => 15,
                "parent_id" => 11,
                "company_id" => 1,
                "added_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 13,
                "name" => strtoupper("PROPERTY PLANT AND EQUIPMENTS"),
                "code" => "01",
                "account_id" => 7,
                "parent_id" => 0,
                "company_id" => 1,
                "added_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 14,
                "name" => strtoupper("VEHICLES- OWNED"),
                "code" => "001",
                "account_id" => 7,
                "parent_id" => 13,
                "company_id" => 1,
                "added_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 15,
                "name" => strtoupper("STORE AND SPARES"),
                "code" => "02",
                "account_id" => 6,
                "parent_id" => 0,
                "company_id" => 1,
                "added_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 16,
                "name" => strtoupper("AUTO PARTS"),
                "code" => "001",
                "account_id" => 6,
                "parent_id" => 15,
                "company_id" => 1,
                "added_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 17,
                "name" => strtoupper("LABORATORY EQUIPMENT"),
                "code" => "002",
                "account_id" => 6,
                "parent_id" => 15,
                "company_id" => 1,
                "added_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 18,
                "name" => strtoupper("GENERAL PARTS"),
                "code" => "003",
                "account_id" => 6,
                "parent_id" => 15,
                "company_id" => 1,
                "added_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 19,
                "name" => strtoupper("MECHANICAL PARTS"),
                "code" => "004",
                "account_id" => 6,
                "parent_id" => 15,
                "company_id" => 1,
                "added_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 20,
                "name" => strtoupper("REFINERY PARTS"),
                "code" => "005",
                "account_id" => 6,
                "parent_id" => 15,
                "company_id" => 1,
                "added_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 21,
                "name" => strtoupper("BOILER PARTS"),
                "code" => "006",
                "account_id" => 6,
                "parent_id" => 15,
                "company_id" => 1,
                "added_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 22,
                "name" => strtoupper("ELECTRIC PARTS"),
                "code" => "007",
                "account_id" => 6,
                "parent_id" => 15,
                "company_id" => 1,
                "added_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 23,
                "name" => strtoupper("RO PLANT"),
                "code" => "008",
                "account_id" => 6,
                "parent_id" => 15,
                "company_id" => 1,
                "added_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 24,
                "name" => strtoupper("SANITORY PARTS"),
                "code" => "009",
                "account_id" => 6,
                "parent_id" => 15,
                "company_id" => 1,
                "added_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 25,
                "name" => strtoupper("STATIONERY"),
                "code" => "010",
                "account_id" => 6,
                "parent_id" => 15,
                "company_id" => 1,
                "added_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 26,
                "name" => strtoupper("FUEL PURCHASE"),
                "code" => "011",
                "account_id" => 6,
                "parent_id" => 15,
                "company_id" => 1,
                "added_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 28,
                "name" => strtoupper("REFINERY PARTS"),
                "code" => "012",
                "account_id" => 6,
                "parent_id" => 15,
                "company_id" => 1,
                "added_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 29,
                "name" => strtoupper("CASH AND BANK BALANCES"),
                "code" => "03",
                "account_id" => 6,
                "parent_id" => 0,
                "company_id" => 1,
                "added_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 30,
                "name" => strtoupper("CASH LEDGERS"),
                "code" => "001",
                "account_id" => 6,
                "parent_id" => 29,
                "company_id" => 1,
                "added_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 31,
                "name" => strtoupper("BANK - CURRENT ACCOUNTS"),
                "code" => "002",
                "account_id" => 6,
                "parent_id" => 29,
                "company_id" => 1,
                "added_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 33,
                "name" => strtoupper("SALES TAX PAYABLE"),
                "code" => "02",
                "account_id" => 8,
                "parent_id" => 0,
                "company_id" => 1,
                "added_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 34,
                "name" => strtoupper("SALES TAX - FBR"),
                "code" => "001",
                "account_id" => 8,
                "parent_id" => 33,
                "company_id" => 1,
                "added_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 35,
                "name" => strtoupper("MISCELLANEOUS DEDUCTIONS"),
                "code" => "01",
                "account_id" => 12,
                "parent_id" => 0,
                "company_id" => 1,
                "added_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 36,
                "name" => strtoupper("MANUFACTURING INVENTORY"),
                "code" => "04",
                "account_id" => 6,
                "parent_id" => 0,
                "company_id" => 1,
                "added_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 37,
                "name" => strtoupper("RAW MATERIALS"),
                "code" => "001",
                "account_id" => 6,
                "parent_id" => 36,
                "company_id" => 1,
                "added_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 38,
                "name" => strtoupper("WORK IN PROGRESS (WIP)"),
                "code" => "002",
                "account_id" => 6,
                "parent_id" => 36,
                "company_id" => 1,
                "added_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 39,
                "name" => strtoupper("FINISHED GOODS"),
                "code" => "003",
                "account_id" => 6,
                "parent_id" => 36,
                "company_id" => 1,
                "added_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 40,
                "name" => strtoupper("TRADE CREDITORS"),
                "code" => "03",
                "account_id" => 8,
                "parent_id" => 0,
                "company_id" => 1,
                "added_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 41,
                "name" => strtoupper("AP-SUPPLIERS"),
                "code" => "001",
                "account_id" => 8,
                "parent_id" => 40,
                "company_id" => 1,
                "added_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 42,
                "name" => strtoupper("OBSOLETE PRODUCT EXPENSE"),
                "code" => "002",
                "account_id" => 15,
                "parent_id" => 9,
                "company_id" => 1,
                "added_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 43,
                "name" => strtoupper("TAXES"),
                "code" => "04",
                "account_id" => 15,
                "parent_id" => 0,
                "company_id" => 1,
                "added_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 44,
                "name" => strtoupper("SALES TAX EXPENSES"),
                "code" => "001",
                "account_id" => 15,
                "parent_id" => 43,
                "company_id" => 1,
                "added_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 45,
                "name" => strtoupper("TEST"),
                "code" => "013",
                "account_id" => 6,
                "parent_id" => 15,
                "company_id" => 1,
                "added_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 46,
                "name" => strtoupper("DEMO"),
                "code" => "014",
                "account_id" => 6,
                "parent_id" => 15,
                "company_id" => 1,
                "added_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 47,
                "name" => strtoupper("REPAIR AND MAINTENANCE-MECHANICAL PARTS"),
                "code" => "003",
                "account_id" => 15,
                "parent_id" => 9,
                "company_id" => 1,
                "added_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 48,
                "name" => strtoupper("OTHER EXPENSES"),
                "code" => "05",
                "account_id" => 15,
                "parent_id" => 0,
                "company_id" => 1,
                "added_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 49,
                "name" => strtoupper("MESS EXPENSE"),
                "code" => "001",
                "account_id" => 15,
                "parent_id" => 48,
                "company_id" => 1,
                "added_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 50,
                "name" => strtoupper("ACCOUNT RECEIVABLE"),
                "code" => "05",
                "account_id" => 6,
                "parent_id" => 0,
                "company_id" => 1,
                "added_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 51,
                "name" => strtoupper("SALES LEDGER"),
                "code" => "001",
                "account_id" => 6,
                "parent_id" => 50,
                "company_id" => 1,
                "added_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 52,
                "name" => strtoupper("REPAIR AND MAINTENANCE-AUTO PARTS"),
                "code" => "004",
                "account_id" => 15,
                "parent_id" => 9,
                "company_id" => 1,
                "added_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 53,
                "name" => strtoupper("SSS"),
                "code" => "015",
                "account_id" => 6,
                "parent_id" => 15,
                "company_id" => 1,
                "added_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 54,
                "name" => strtoupper("EMPLOYEE EQUIPMENT OR TOOLS"),
                "code" => "002",
                "account_id" => 7,
                "parent_id" => 13,
                "company_id" => 1,
                "added_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 55,
                "name" => strtoupper("REPAIR AND MAINTENANCE-SSS"),
                "code" => "005",
                "account_id" => 15,
                "parent_id" => 9,
                "company_id" => 1,
                "added_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 56,
                "name" => strtoupper("STATION WISE REVENUE"),
                "code" => "01",
                "account_id" => 13,
                "parent_id" => 0,
                "company_id" => 1,
                "added_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 57,
                "name" => strtoupper("BUS REVENUE"),
                "code" => "01",
                "account_id" => 13,
                "parent_id" => 56,
                "company_id" => 1,
                "added_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 58,
                "name" => strtoupper("ACCOUNT PAYABLE"),
                "code" => "01",
                "account_id" => 8,
                "parent_id" => 0,
                "company_id" => 1,
                "added_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 59,
                "name" => strtoupper("Service/Vendor Payable"),
                "code" => "01",
                "account_id" => 8,
                "parent_id" => 58,
                "company_id" => 1,
                "added_by" => 0,
                "created_at" => now(),
                "updated_at" => now(),
            ],
        ]);

        AccountHead::create([
            'name' => strtoupper("CASH IN HAND |CASH LEDGER"),
            'code' => "0001",
            'parent_account_id' => 1,// ASSETS
            'account_id' => 6,// CURRENT ASSETS
            'parent_group_id' => 29,// CASH AND BANK BALANCES
            'group_id' => 30,// CASH LEDGERS
            'added_by' => 0,
            'company_id' => 1,
        ]);

        Cash::create([
            "amount" => 0,
            "account_head_id" => 1,
            'added_by' => 0,
            "company_id" => 1
        ]);
    }
}

