<?php

namespace Database\Seeders;

use App\Models\Account\Account;
use Illuminate\Database\Seeder;

class AccountsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Account::create(
            [
            'name'=> 'Assets',
            'code'=> '01',
            'parent_id'=> '0',
            'added_by'=> '0',
            'updated_by'=> null,
            'updated_at'=> null,
            'created_at'=> null,
            'deleted_at'=> null,
            ],
            [
            'name'=> 'Liabilities',
            'code'=> '02',
            'parent_id'=> '0',
            'added_by'=> '0',
            'updated_by'=> null,
            'updated_at'=> null,
            'created_at'=> null,
            'deleted_at'=> null,
            ],
            [
            'name'=> 'Equity',
            'code'=> '03',
            'parent_id'=> '0',
            'added_by'=> '0',
            'updated_by'=> null,
            'updated_at'=> null,
            'created_at'=> null,
            'deleted_at'=> null,
            ],
            [
            'name'=> 'Revenue',
            'code'=> '04',
            'parent_id'=> '0',
            'added_by'=> '0',
            'updated_by'=> null,
            'updated_at'=> null,
            'created_at'=> null,
            'deleted_at'=> null,
            ],
            [
            'name'=> 'Expenses',
            'code'=> '05',
            'parent_id'=> '0',
            'added_by'=> '0',
            'updated_by'=> null,
            'updated_at'=> null,
            'created_at'=> null,
            'deleted_at'=> null,
            ],
            [
            'name'=> 'Current Assets',
            'code'=> '15',
            'parent_id'=> '1',
            'added_by'=> '0',
            'updated_by'=> null,
            'updated_at'=> null,
            'created_at'=> null,
            'deleted_at'=> null,
            ],
            [
            'name'=> 'Non Current Assets',
            'code'=> '10',
            'parent_id'=> '1',
            'added_by'=> '0',
            'updated_by'=> null,
            'updated_at'=> null,
            'created_at'=> null,
            'deleted_at'=> null,
            ],
            [
            'name'=> 'Cash & Bank Balances',
            'code'=> '16',
            'parent_id'=> '1',
            'added_by'=> '0',
            'updated_by'=> null,
            'updated_at'=> null,
            'created_at'=> null,
            'deleted_at'=> null,
            ],
            [
            'name'=> 'Current Liabilities',
            'code'=> '40',
            'parent_id'=> '2',
            'added_by'=> '0',
            'updated_by'=> null,
            'updated_at'=> null,
            'created_at'=> null,
            'deleted_at'=> null,
            ],
            [
            'name'=> 'Non Current Liabilities',
            'code'=> '31',
            'parent_id'=> '2',
            'added_by'=> '0',
            'updated_by'=> null,
            'updated_at'=> null,
            'created_at'=> null,
            'deleted_at'=> null,
            ],
            [
            'name'=> 'Shared Equity',
            'code'=> '21',
            'parent_id'=> '3',
            'added_by'=> '0',
            'updated_by'=> null,
            'updated_at'=> null,
            'created_at'=> null,
            'deleted_at'=> null,
            ],
            [
            'name'=> 'Retained Earning',
            'code'=> '22',
            'parent_id'=> '3',
            'added_by'=> '0',
            'updated_by'=> null,
            'updated_at'=> null,
            'created_at'=> null,
            'deleted_at'=> null,
            ],
            [
            'name'=> 'Net Sales',
            'code'=> '50',
            'parent_id'=> '4',
            'added_by'=> '0',
            'updated_by'=> null,
            'updated_at'=> null,
            'created_at'=> null,
            'deleted_at'=> null,
            ],
            [
            'name'=> 'Other Comprehensive',
            'code'=> '95',
            'parent_id'=> '4',
            'added_by'=> '0',
            'updated_by'=> null,
            'updated_at'=> null,
            'created_at'=> null,
            'deleted_at'=> null,
            ],
            [
            'name'=> 'Other Income & Losses',
            'code'=> '85',
            'parent_id'=> '4',
            'added_by'=> '0',
            'updated_by'=> null,
            'updated_at'=> null,
            'created_at'=> null,
            'deleted_at'=> null,
            ],
            [
            'name'=> 'Cost of Goods Sold',
            'code'=> '60',
            'parent_id'=> '5',
            'added_by'=> '0',
            'updated_by'=> null,
            'updated_at'=> null,
            'created_at'=> null,
            'deleted_at'=> null,
            ],
            [
            'name'=> 'Operating Expenses',
            'code'=> '70',
            'parent_id'=> '5',
            'added_by'=> '0',
            'updated_by'=> null,
            'updated_at'=> null,
            'created_at'=> null,
            'deleted_at'=> null,
            ],
            [
            'name'=> 'Finance Cost',
            'code'=> '80',
            'parent_id'=> '5',
            'added_by'=> '0',
            'updated_by'=> null,
            'updated_at'=> null,
            'created_at'=> null,
            'deleted_at'=> null,
            ],
            [
            'name'=> 'Provision of Taxation',
            'code'=> '90',
            'parent_id'=> '5',
            'added_by'=> '0',
            'updated_by'=> null,
            'updated_at'=> null,
            'created_at'=> null,
            'deleted_at'=> null,
            ]
    );
    }
}
